// Per-install API token. Generated by the server on first run and served from
// /token; cached in chrome.storage. Fetching it is ASYNC, so every authed call
// goes through kamFetch(), which waits for the token before sending. Otherwise a
// click made before the token arrives sends an empty header and gets a 403.
let KAM_TOKEN = "";
let _tokenPromise = null;
function _ensureToken() {
  if (KAM_TOKEN) return Promise.resolve(KAM_TOKEN);
  if (_tokenPromise) return _tokenPromise;          // one in-flight fetch, shared
  _tokenPromise = (async () => {
    try {
      const st = await chrome.storage.local.get("kamToken");
      if (st.kamToken) { KAM_TOKEN = st.kamToken; return KAM_TOKEN; }
    } catch (e) {}
    try {
      const r = await fetch("http://127.0.0.1:5050/token");
      if (r.ok) {
        KAM_TOKEN = (await r.json()).token || "";
        if (KAM_TOKEN) chrome.storage.local.set({ kamToken: KAM_TOKEN });
      }
    } catch (e) { /* server down — retried on the next call */ }
    _tokenPromise = null;                            // allow a later retry
    return KAM_TOKEN;
  })();
  return _tokenPromise;
}

// Drop-in replacement for fetch() on authed server endpoints: waits for the
// token, then injects the header. Returns the same promise shape as fetch.
async function kamFetch(url, opts = {}) {
  const tok = await _ensureToken();
  return fetch(url, Object.assign({}, opts, {
    headers: Object.assign({}, opts.headers || {}, { "X-KAM-Token": tok })
  }));
}
_ensureToken();   // warm the cache as soon as the popup opens

const SERVER = "http://127.0.0.1:5050";
let currentMode       = "selection";
let allChunks         = [];
let currentChunkIndex = 0;


// Strip semantic markers from chunk text before displaying in the UI.
// The markers are only for the TTS server, so what you see stays clean.
// --- Theme & reading overlay settings ---
// Three themes live in popup.html as [data-theme="..."] palettes; here we
// persist the user's choice and reapply it on every popup open. Overlay
// settings (line colour + text size) live in chrome.storage.local so the
// content-script overlay can read them without round-tripping through the
// background worker.
const POPUP_SETTINGS_DEFAULTS = {
  popupTheme:        "arian",
  overlayLineColour: "#f5c518",   // effective highlight colour (derived)
  overlayBarColour:  "#0f0f0f",   // effective bar background colour (derived)
  overlayTextSize:   12,
  // Per-theme custom colours. Every theme is now customisable; these seed the
  // pickers and are what the effective colours are derived from. Defaults are
  // the tuned presets for each theme.
  themeColours: {
    arian: { highlight: "#f5c518", bar: "#0f0f0f" },
    light: { highlight: "#0078d4", bar: "#ffffff" },
    dark:  { highlight: "#4cc2ff", bar: "#1b1a19" },
  },
};

// Factory defaults per theme, used by the "reset this theme" button.
const THEME_COLOUR_DEFAULTS = {
  arian: { highlight: "#f5c518", bar: "#0f0f0f" },
  light: { highlight: "#0078d4", bar: "#ffffff" },
  dark:  { highlight: "#4cc2ff", bar: "#1b1a19" },
};

function applyPopupTheme(name) {
  const valid = ["arian", "light", "dark"];
  if (!valid.includes(name)) name = "arian";
  document.body.setAttribute("data-theme", name);
  document.querySelectorAll(".theme-btn").forEach(b => {
    b.classList.toggle("active", b.dataset.theme === name);
  });
}

function initSettings() {
  let _activeTheme = "arian";
  let _themeColours = JSON.parse(JSON.stringify(POPUP_SETTINGS_DEFAULTS.themeColours));

  const hlPicker  = document.getElementById("ov-hl-colour");
  const hlVal     = document.getElementById("ov-hl-colour-val");
  const barPicker = document.getElementById("ov-bar-colour");
  const barVal    = document.getElementById("ov-bar-colour-val");
  const themeName = document.getElementById("cust-theme-name");

  // Paint the pickers + effective colours for the active theme, and persist the
  // effective colours so content.js (overlay + highlight) updates live.
  function reflectTheme(theme) {
    // Guard every layer: an old or partial stored themeColours, or an unknown
    // theme name, must never crash the popup. Fall back to defaults, then to a
    // safe literal.
    theme = theme || "arian";
    _activeTheme = theme;
    const c = (_themeColours && _themeColours[theme])
              || THEME_COLOUR_DEFAULTS[theme]
              || THEME_COLOUR_DEFAULTS.arian
              || { highlight: "#f5c518", bar: "#0f0f0f" };
    if (hlPicker)  hlPicker.value  = c.highlight;
    if (hlVal)     hlVal.textContent = c.highlight;
    if (barPicker) barPicker.value = c.bar;
    if (barVal)    barVal.textContent = c.bar;
    if (themeName) themeName.textContent =
      theme.charAt(0).toUpperCase() + theme.slice(1) + " · highlight colour";
    chrome.storage.local.set({
      overlayLineColour: c.highlight,
      overlayBarColour:  c.bar,
    });
  }

  chrome.storage.local.get(POPUP_SETTINGS_DEFAULTS, (cfg) => {
    // Merge stored colours OVER the full defaults, so a partial/old stored
    // object (missing a theme) still yields a complete map.
    _themeColours = Object.assign(
      {}, JSON.parse(JSON.stringify(THEME_COLOUR_DEFAULTS)), cfg.themeColours || {}
    );
    // Ensure each theme entry is itself complete.
    for (const t of Object.keys(THEME_COLOUR_DEFAULTS)) {
      _themeColours[t] = Object.assign({}, THEME_COLOUR_DEFAULTS[t], _themeColours[t] || {});
    }
    applyPopupTheme(cfg.popupTheme);
    reflectTheme(cfg.popupTheme);

    const ovSize    = document.getElementById("ov-size");
    const ovSizeVal = document.getElementById("ov-size-val");
    if (ovSize)    ovSize.value = cfg.overlayTextSize;
    if (ovSizeVal) ovSizeVal.textContent = cfg.overlayTextSize + "px";
  });

  // Theme buttons, which switch the theme and load that theme's saved colours
  // into the pickers.
  document.querySelectorAll(".theme-btn").forEach(btn => {
    btn.addEventListener("click", () => {
      const theme = btn.dataset.theme;
      applyPopupTheme(theme);
      chrome.storage.local.set({ popupTheme: theme });
      reflectTheme(theme);
    });
  });

  // Collapsible panel.
  const toggle = document.getElementById("settings-toggle");
  const panel  = document.getElementById("settings-panel");
  if (toggle && panel) {
    chrome.storage.local.get({ settingsOpen: false }, d => {
      panel.style.display = d.settingsOpen ? "block" : "none";
    });
    toggle.addEventListener("click", () => {
      const open = panel.style.display !== "block";
      panel.style.display = open ? "block" : "none";
      chrome.storage.local.set({ settingsOpen: open });
    });
  }

  // Persist a colour edit into the ACTIVE theme's profile + push effective.
  function saveColour(kind, value) {
    if (!_themeColours[_activeTheme]) _themeColours[_activeTheme] = {};
    _themeColours[_activeTheme][kind] = value;
    const eff = _themeColours[_activeTheme];
    chrome.storage.local.set({
      themeColours: _themeColours,
      overlayLineColour: eff.highlight,
      overlayBarColour:  eff.bar,
    });
  }

  if (hlPicker) {
    hlPicker.addEventListener("input", () => {
      hlVal.textContent = hlPicker.value;
      saveColour("highlight", hlPicker.value);
    });
  }
  if (barPicker) {
    barPicker.addEventListener("input", () => {
      barVal.textContent = barPicker.value;
      saveColour("bar", barPicker.value);
    });
  }

  // Reset the active theme's colours to factory defaults.
  const resetBtn = document.getElementById("reset-theme-colours");
  if (resetBtn) {
    resetBtn.addEventListener("click", () => {
      const d = THEME_COLOUR_DEFAULTS[_activeTheme] || THEME_COLOUR_DEFAULTS.dark;
      _themeColours[_activeTheme] = { highlight: d.highlight, bar: d.bar };
      reflectTheme(_activeTheme);
      chrome.storage.local.set({ themeColours: _themeColours });
    });
  }

  // Reading-overlay text size (theme-independent).
  const ovSize = document.getElementById("ov-size");
  if (ovSize) {
    ovSize.addEventListener("input", () => {
      const v = parseInt(ovSize.value, 10);
      document.getElementById("ov-size-val").textContent = v + "px";
      chrome.storage.local.set({ overlayTextSize: v });
    });
  }
}


function stripMarkersForDisplay(text) {
  return text
    .replace(/\|\/?(H[1-3]|BOLD|ITALIC|CODE|CALLOUT|CAPTION)\|/g, '')
    .replace(/\|BREAK\|/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

document.addEventListener("DOMContentLoaded", () => {
  // Keep temperature in sync with the server (and thus the tuning dropdown) when
  // the popup gets focus back, which covers having both UIs open at once.
  window.addEventListener("focus", () => {
    kamFetch("http://127.0.0.1:5050/settings", {})
      .then(r => r.json())
      .then(s => {
        if (!s) return;
        const ts = document.getElementById("temp-slider");
        if (s.temperature != null && ts && parseFloat(ts.value) !== s.temperature) {
          ts.value = s.temperature;
          updateTemperature(s.temperature, true);
        }
        const sp = document.getElementById("speed-slider");
        if (s.speed != null && sp && parseFloat(sp.value) !== s.speed) {
          sp.value = s.speed;
          updateSpeed(s.speed, true);
        }
      }).catch(() => {});
  });
  initSettings();
  checkServer();
  checkIfPlaying();
  const ll = document.getElementById("learner-link");
  if (ll) ll.addEventListener("click", (e) => {
    e.preventDefault();
    const _pUrl = chrome.runtime.getURL("player.html");
  chrome.tabs.query({ url: _pUrl }, tabs => {
    if (tabs && tabs.length > 0) chrome.tabs.update(tabs[0].id, { active: true });
    else chrome.tabs.create({ url: _pUrl, active: true });
  });
  });
  document.getElementById("speak-btn").addEventListener("click", speak);
  document.getElementById("stop-btn").addEventListener("click", stopAudio);

  // The dashboard button, which opens the full Chunks, Report, Rules and AI UI.
  const dashBtn = document.getElementById("open-dashboard");
  if (dashBtn) dashBtn.addEventListener("click", () => { openDashboard(); window.close(); });

  // Page-highlight toggle. State lives in chrome.storage.local; content.js
  // reacts instantly via its storage listener. We just flip the value and
  // reflect it on the button label/style.
  const hlBtn = document.getElementById("toggle-highlight");
  if (hlBtn) {
    const paintHlBtn = (on) => {
      hlBtn.textContent = on ? "✏️ Page Highlight: On" : "✏️ Page Highlight: Off";
      hlBtn.classList.toggle("off", !on);
    };
    chrome.storage.local.get({ highlightEnabled: true }, c => paintHlBtn(c.highlightEnabled !== false));
    hlBtn.addEventListener("click", () => {
      chrome.storage.local.get({ highlightEnabled: true }, c => {
        const next = !(c.highlightEnabled !== false);
        chrome.storage.local.set({ highlightEnabled: next }, () => paintHlBtn(next));
      });
    });
  }

  // Header-bar toggle. Same storage-backed pattern: content.js shows/hides the
  // overlay bar instantly via its storage listener.
  const barBtn = document.getElementById("toggle-headerbar");
  if (barBtn) {
    const paintBarBtn = (on) => {
      barBtn.textContent = on ? "📋 Header Bar: On" : "📋 Header Bar: Off";
      barBtn.classList.toggle("off", !on);
    };
    chrome.storage.local.get({ overlayEnabled: true }, c => paintBarBtn(c.overlayEnabled !== false));
    barBtn.addEventListener("click", () => {
      chrome.storage.local.get({ overlayEnabled: true }, c => {
        const next = !(c.overlayEnabled !== false);
        chrome.storage.local.set({ overlayEnabled: next }, () => paintBarBtn(next));
      });
    });
  }

  // Feedback buttons (moved off inline onclick for MV3 CSP compliance).
  const fbUp   = document.getElementById("fb-up-btn");
  const fbDown = document.getElementById("fb-down-btn");
  if (fbUp)   fbUp.addEventListener("click", thumbsUp);
  if (fbDown) fbDown.addEventListener("click", thumbsDown);
  document.getElementById("tab-selection").addEventListener("click", () => setMode("selection"));
  document.getElementById("tab-custom").addEventListener("click", () => setMode("custom"));
  document.getElementById("tab-page").addEventListener("click", () => setMode("page"));
  document.getElementById("speed-slider").addEventListener("input", (e) => updateSpeed(e.target.value));
  document.getElementById("temp-slider").addEventListener("input", (e) => updateTemperature(e.target.value));
  document.getElementById("btn-pause").addEventListener("click", () => {
    chrome.runtime.sendMessage({ action: "pauseResume" }).catch(() => {});
  });
  // Temperature and speed: the server's live values are the single source of
  // truth (the tuning dropdown writes to them too). Read on open so popup and
  // dropdown always agree. Fall back to local storage if the server is down.
  kamFetch("http://127.0.0.1:5050/settings", {
  })
    .then(r => r.json())
    .then(s => {
      const ts = document.getElementById("temp-slider");
      if (s && s.temperature != null && ts) { ts.value = s.temperature; updateTemperature(s.temperature, true); }
      const sp = document.getElementById("speed-slider");
      if (s && s.speed != null && sp) {
        sp.value = s.speed;
        document.getElementById("speed-value").textContent = `${parseFloat(s.speed).toFixed(2)}x`;
        chrome.runtime.sendMessage({ action: "setSpeed", speed: s.speed }).catch(() => {});
      }
      chrome.storage.local.set({ temperature: s && s.temperature, speed: s && s.speed });
    })
    .catch(() => {
      chrome.storage.local.get(['temperature', 'speed'], (data) => {
        if (data.temperature) {
          const ts = document.getElementById("temp-slider");
          if (ts) { ts.value = data.temperature; updateTemperature(data.temperature, true); }
        }
        if (data.speed) {
          const sp = document.getElementById("speed-slider");
          if (sp) { sp.value = data.speed; document.getElementById("speed-value").textContent = `${parseFloat(data.speed).toFixed(2)}x`; }
        }
      });
    });
});

function checkIfPlaying() {
  chrome.runtime.sendMessage({ action: "getStatus" }, (response) => {
    if (response && response.isPlaying) {
      allChunks         = response.chunks || [];
      currentChunkIndex = response.currentChunkIndex || 0;
      showPlayer(true);
      updatePlayerLabel(currentChunkIndex + 1, allChunks.length);
      updateProgressFill(currentChunkIndex + 1, allChunks.length);
      renderTextView(allChunks, currentChunkIndex);
      document.getElementById("speak-btn").disabled = true;
      const paused = response.isPaused;
      document.getElementById("btn-pause").textContent    = paused ? "▶" : "⏸";
      document.getElementById("btn-pause").classList.toggle("paused", paused);
    }
  });
}

chrome.runtime.onMessage.addListener((request) => {
  if (request.action === "chunkStatus") {
    currentChunkIndex = request.current - 1;
    updatePlayerLabel(request.current, request.total);
    updateActiveChunk(currentChunkIndex);
    updateProgressFill(request.current, request.total);
  }
  if (request.action === "playbackFinished") {
    showPlayer(false);
    document.getElementById("speak-btn").disabled = false;
    document.getElementById("text-view").style.display = "none";
    allChunks = [];
  }
  if (request.action === "pausedPlaying") {
    const btn = document.getElementById("btn-pause");
    if (btn) { btn.textContent = "▶"; btn.classList.add("paused"); }
  }
  if (request.action === "resumedPlaying") {
    const btn = document.getElementById("btn-pause");
    if (btn) { btn.textContent = "⏸"; btn.classList.remove("paused"); }
  }
  if (request.action === "chunkReady") {
    _lastChunkId   = request.chunkId   || null;
    _lastChunkText = request.chunkText || "";
    _showFeedbackButtons();
  }
});

// --- Quality feedback ---
let _lastChunkId   = null;
let _lastChunkText = "";
let _feedbackOpen  = false;

function _showFeedbackButtons() {
  const bar = document.getElementById("feedback-bar");
  if (bar) bar.style.display = "flex";
}
function _hideFeedbackButtons() {
  const bar = document.getElementById("feedback-bar");
  if (bar) bar.style.display = "none";
  _feedbackOpen = false;
}

function thumbsUp() {
  kamFetch("http://127.0.0.1:5050/report", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ chunk_id: _lastChunkId, chunk_text: _lastChunkText, issue: "OTHER", action: "IGNORE", confidence: "HIGH", notes: "user_approved" })
  }).catch(() => {});
  _hideFeedbackButtons();
}

function thumbsDown() {
  const url = chrome.runtime.getURL("player.html") + "#report:" + encodeURIComponent(_lastChunkText || "");
  chrome.tabs.query({ url: chrome.runtime.getURL("player.html") }, tabs => {
    if (tabs && tabs.length > 0) chrome.tabs.update(tabs[0].id, { url, active: true });
    else chrome.tabs.create({ url, active: true });
  });
  _hideFeedbackButtons();
}

function openDashboard() {
  const url = chrome.runtime.getURL("player.html");
  chrome.tabs.query({ url }, tabs => {
    if (tabs && tabs.length > 0) chrome.tabs.update(tabs[0].id, { active: true });
    else chrome.tabs.create({ url, active: true });
  });
}

async function checkServer() {
  // The fetch verdict is computed FIRST and every DOM update is null-safe.
  // A previous version updated elements inside the try block, so a missing
  // or renamed element, which happened after theme edits to popup.html, threw
  // after a successful health check and quietly painted "Server offline".
  let online = false;
  try {
    // 3-second timeout so we never hang on "Checking server..."
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 3000);
    const res  = await fetch(`${SERVER}/health`, { signal: controller.signal });
    clearTimeout(timer);
    online = res.ok;
    if (!res.ok) console.warn("[KAM] health check: server answered", res.status);
  } catch (err) {
    // A server that simply isn't running yet throws "Failed to fetch" or an
    // AbortError on timeout. That is the expected pre-start state, polled every
    // 3s, so I don't log it as an error since that just spams the console. Any
    // other unexpected error still gets surfaced.
    const expected = err && (err.name === "AbortError" ||
                             /Failed to fetch|NetworkError/i.test(String(err.message || err)));
    if (!expected) console.error("[KAM] health check failed:", err);
  }
  const dot = document.getElementById("status-dot");
  const txt = document.getElementById("status-text");
  const btn = document.getElementById("speak-btn");
  if (dot) dot.className = online ? "status-dot online" : "status-dot offline";
  if (txt) txt.textContent = online ? "Server online" : "Server offline. Start server.py";
  if (btn) btn.disabled = !online;
  if (!online) setTimeout(checkServer, 3000);   // retry every 3 seconds
}

function setMode(mode) {
  currentMode = mode;
  ["selection", "custom", "page"].forEach(m => {
    document.getElementById(`tab-${m}`).classList.toggle("active", m === mode);
  });
  document.getElementById("custom-text-area").style.display = mode === "custom" ? "block" : "none";
}

function updateSpeed(val, skipPost) {
  const speed = parseFloat(val);
  document.getElementById("speed-value").textContent = `${speed.toFixed(2)}x`;
  chrome.runtime.sendMessage({ action: "setSpeed", speed }).catch(() => {});
  // Mirror to the server so the tuning dropdown's Speed slider stays in sync
  // (skipPost avoids echoing a value we just read from the server).
  if (!skipPost) {
    kamFetch("http://127.0.0.1:5050/settings", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ speed })
    }).catch(() => {});
    chrome.storage.local.set({ speed });
  }
}

function updateTemperature(val, skipPost) {
  const temp = parseFloat(val);
  document.getElementById("temp-value").textContent = temp.toFixed(2);

  // Gradient track: blue (cold 0.05) → red (hot 0.90)
  const pct = ((temp - 0.05) / (0.90 - 0.05)) * 100;
  // Interpolate hue: 220 (blue) → 0 (red)
  const hue  = Math.round(220 - (220 * pct / 100));
  const fill = `hsl(${hue},90%,55%)`;
  const slider = document.getElementById("temp-slider");
  if (slider) {
    slider.style.accentColor = fill;
    slider.style.setProperty("--fill", fill);
    slider.style.background =
      `linear-gradient(to right, ${fill} ${pct}%, #2a2a2a ${pct}%)`;
  }

  // Send to server live (unless we're just reflecting a value we read FROM the
  // server, which would be a redundant echo).
  if (!skipPost) {
    kamFetch("http://127.0.0.1:5050/settings", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ temperature: temp })
    }).catch(() => {});
    chrome.storage.local.set({ temperature: temp });
  }
}

function stopAudio() {
  chrome.runtime.sendMessage({ action: "stop" }).catch(() => {});
  showPlayer(false);
  document.getElementById("speak-btn").disabled = false;
  document.getElementById("text-view").style.display = "none";
  allChunks = [];
}

async function speak() {
  hideError();
  let text = "";

  // Stage feedback: the first action after a cold start does real work (waking
  // the service worker, fetching the token, waking the model from standby).
  // Without visible progress that delay reads as a broken model.
  showInfo("⏳ Preparing…");
  if (currentMode === "custom") {
    text = document.getElementById("custom-input").value.trim();
    if (!text) { showError("Please type some text first."); return; }
  } else if (currentMode === "page") {
    showInfo("⏳ Reading the page…");
    text = await _withExtractionTimeout(getPageText());
    if (text === "__KAM_NO_PAGE__") {
      showError("Switch to a web page tab first — KAM can't read its own dashboard or chrome:// pages.");
      return;
    }
    if (text === "__KAM_TIMEOUT__") {
      showError("The page did not respond in time. Reload the tab and try again — "
              + "some pages block extensions until they finish loading.");
      return;
    }

    if (!text) { showError("Could not extract text from page."); return; }
  } else {
    showInfo("⏳ Reading your selection…");
    text = await _withExtractionTimeout(getSelectedText());
    if (text === "__KAM_NO_PAGE__") {
      showError("Switch to a web page tab first — KAM can't read its own dashboard or chrome:// pages.");
      return;
    }
    if (text === "__KAM_TIMEOUT__") {
      showError("The page did not respond in time. Reload the tab and try again — "
              + "some pages block extensions until they finish loading.");
      return;
    }

    if (!text) { showError("No text selected. Highlight text on the page first."); return; }
  }

  showInfo("⏳ Splitting into chunks…");
  allChunks = splitIntoChunks(text);
  allChunks = await applyBoundaryCorrections(allChunks);

  // Always show diagnostic so problems are visible
  const _breaks = (text.match(/\|BREAK\|/g) || []).length;
  if (allChunks.length === 0) {
    showError("No content found — " + text.length + "c, " + _breaks + " breaks");
    return;
  }
  // Debug logging for chunk diagnosis used to live here and has been removed
  const _orphans = allChunks.filter(c => /^(and|but|or|so|yet|nor|for)\b/i.test(c) && c.length <= 50);
  showInfo(allChunks.length + " chunk" + (allChunks.length === 1 ? "" : "s") +
    " · " + text.length + "c · " + _breaks + " breaks" +
    (_orphans.length > 0 ? " · ⚠ " + _orphans.length + " orphan(s)" : " · ✓ clean"));

  currentChunkIndex = 0;
  const speed = parseFloat(document.getElementById("speed-slider").value);

  showPlayer(true);
  updatePlayerLabel(1, allChunks.length);
  updateProgressFill(1, allChunks.length);
  renderTextView(allChunks, 0);
  document.getElementById("speak-btn").disabled = true;

  chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
    if (!tabs || !tabs[0]) {
      showError("No active tab found — cannot start playback."); return;
    }
    const tabId = tabs[0].id;
    // Unique nonce prevents background.js processing the same session twice
    // even if Chrome delivers the message more than once during SW wake-up.
    const nonce = Date.now() + '-' + Math.random().toString(36).slice(2);
    // Solid digestion (learning from heard-but-unrated chunks) applies only to
    // real reading content, so Read Page and Selected Text. Custom Text is
    // one-off typed input and shouldn't shape the per-sentence-type learning.
    const digestible = (currentMode === "page" || currentMode === "selection");
    chrome.runtime.sendMessage(
      { action: "startSpeaking", chunks: allChunks, startIndex: 0, speed, tabId, nonce, digestible },
      (response) => {
        if (chrome.runtime.lastError || !response) {
          showError("Background worker unreachable — reload the extension.");
          showPlayer(false);
          document.getElementById("speak-btn").disabled = false;
        }
      }
    );
  });
}

// =============================================================================
// ADAPTIVE CHUNKING
//
// Philosophy:
//   Every chunk should be a natural spoken unit, so consistent in length,
//   coherent in context, and matched to how that content type is actually
//   spoken aloud. The system has four layers:
//
//   1. Segment classification. classifySegment() reads each |BREAK| segment and
//      works out its type: narrative, technical, list, heading or callout.
//      This drives all downstream packing decisions.
//
//   2. Content-aware targets. targetFor() returns the ideal chunk length for a
//      piece of text based on what's in it, so questions, emphasis,
//      definitions, list items). Pre-compiled regexes, no repeated construction.
//
//   3. The greedy packer, which groups sentences into chunks while respecting
//      the targets and the segment type. Narrative prose packs aggressively and
//      technical content
//      stays tighter; list items never merge across items.
//
//   4. The safety net, where oversized chunks split on clause boundaries and
//      anything still too long gets hard-split at word boundaries.
// =============================================================================

const TARGET_CHARS = 90;    // target chunk length — keeps XTTS inference fast
const MAX_CHARS    = 150;   // hard cap — one sentence max, never cut mid-phrase
const MIN_CHARS    = 6;     // discard anything shorter

// ---------------------------------------------------------------------------
// Pre-compiled patterns, built once at module load and never rebuilt
// ---------------------------------------------------------------------------

const _RX_QUESTION    = /[?]/;
const _RX_EMPHASIS    = /[|](BOLD|ITALIC)[|]/;
const _RX_COLON       = /:\s*\S/;
const _RX_EXCLAIM_END = /[!]$/;
const _RX_MAIN_VERB   = /\b(is|are|was|were|has|have|will|can|should|does|did|provides|allows|enables|supports|requires|returns|creates|defines|makes|gives|takes|uses|runs|works|helps|lets|gets|sets|puts|adds|removes|handles|manages|controls|builds|shows|displays|describes|explains|represents|refers|means|indicates)\b/i;
const _RX_LETTERS     = /[a-zA-Z]/;
const _RX_WHITESPACE  = /\s+/;

// Transition words, since these sentences should attach to what follows them
const _RX_TRANSITION  = /^(however|therefore|furthermore|additionally|consequently|nevertheless|in addition|in contrast|on the other hand|as a result|for example|for instance|in other words|that is|specifically|notably|importantly|finally|first|second|third|next|then|lastly|in summary|to summarise|to conclude)\b/i;

// List item starters, which signal an enumeration context
const _RX_LIST_START  = /^(\d+[.)]\s|\*\s|[-•]\s|[a-z][.)]\s)/;

// Heading-like patterns, so short, title-cased and with no verb
const _RX_HEADING_EXCL = /\b(is|are|was|were|has|have|will|can|could|should|do|does|did|what|when|where|which|who|why|how)\b/i;


// ---------------------------------------------------------------------------
// Segment classifier
// ---------------------------------------------------------------------------
// Reads the opening of a |BREAK| segment and classifies its intent.
// Called once per segment, and it drives the packing strategy for that segment.
//
// The types are:
//   'heading'    short title-like text with no main verb
//   'list'       a segment holding several short itemised sentences
//   'callout'    a note, warning or tip block
//   'technical'  contains code markers, abbreviations or definitions
//   'narrative'  flowing prose where the sentences build on each other
//   'default'    the fallback

function classifySegment(seg) {
  const words = seg.trim().split(_RX_WHITESPACE);
  const hasSentenceBreak = /[.!?]\s+[A-Z]/.test(seg);
  const hasAbbrev        = /\b[A-Z]{2,}\b/.test(seg);

  // Heading: whole segment short, no internal sentence breaks, no abbreviations
  if (words.length <= 10 && !hasSentenceBreak && !hasAbbrev &&
      !_RX_HEADING_EXCL.test(seg.substring(0, 60))) {
    const cap = words.filter(w => w && w[0] === w[0].toUpperCase() && w[0] !== w[0].toLowerCase()).length;
    if (words.length > 0 && cap / words.length >= 0.55) return 'heading';
  }

  // Callout
  if (/^\s*(note|warning|tip|important|caution|example|info|danger|hint)\b/i.test(seg))
    return 'callout';

  // List: multiple sentences, mostly short and verbless
  const sentences = seg.split(/[.!?]+\s+/).filter(s => s.trim());
  if (sentences.length >= 2) {
    const shortCount  = sentences.filter(s => s.split(_RX_WHITESPACE).length <= 12).length;
    const verblessCnt = sentences.filter(s => !_RX_MAIN_VERB.test(s)).length;
    if (shortCount  / sentences.length >= 0.7 &&
        verblessCnt / sentences.length >= 0.5) return 'list';
  }

  // Technical: emphasis markers or abbreviation + definition pattern
  if (_RX_EMPHASIS.test(seg) || /[|]CODE[|]/.test(seg)) return 'technical';
  if (hasAbbrev && _RX_COLON.test(seg))                  return 'technical';

  // Narrative is flowing prose, so 6 or more words a sentence across several
  if (sentences.length >= 2 && words.length / sentences.length >= 6)
    return 'narrative';

  return 'default';
}



// ---------------------------------------------------------------------------
// Content-aware target sizing
// ---------------------------------------------------------------------------

function targetFor(text) {
  if (_RX_QUESTION.test(text))   return MAX_CHARS;  // never split questions
  if (_RX_EMPHASIS.test(text))   return MAX_CHARS;  // keep emphasis whole
  if (_RX_COLON.test(text))      return TARGET_CHARS; // definitions need context

  const wordCount = text.trim().split(_RX_WHITESPACE).length;
  if (wordCount <= 12 && !_RX_MAIN_VERB.test(text)) return 85; // list item
  if (_RX_EXCLAIM_END.test(text.trim()))              return 90; // exclamation

  return TARGET_CHARS;
}


// ---------------------------------------------------------------------------
// The minimum readable length, which is a context-aware floor
// ---------------------------------------------------------------------------

function minFor(text) {
  if (_RX_EMPHASIS.test(text)) return 20;
  if (_RX_QUESTION.test(text) || _RX_EXCLAIM_END.test(text)) return 15;
  return MIN_CHARS;
}


// ---------------------------------------------------------------------------
// Emphasis boundary guard
// ---------------------------------------------------------------------------

// Apply learned chunk-boundary corrections. The user reports (via the Report
// page) any fragment that was wrongly split off from its sentence; the server
// stores it. Here we fetch those fragments and re-merge: any chunk that begins
// with a known fragment is joined back onto the previous chunk, fixing the
// mis-split on every future read. It's guarded, so a failed fetch just leaves
// the chunks as they are.
async function applyBoundaryCorrections(chunks) {
  if (!Array.isArray(chunks) || chunks.length < 2) return chunks;
  let fragments = [];
  try {
    const res = await kamFetch(`${SERVER}/rules/boundary`, {});
    if (res.ok) {
      const data = await res.json();
      fragments = (data.fragments || []).map(f => String(f).trim()).filter(Boolean);
    }
  } catch (e) {
    return chunks;   // server offline or error: chunk as normal
  }
  if (!fragments.length) return chunks;

  const norm = s => s.replace(/\s+/g, " ").trim().toLowerCase();
  const fragNorms = fragments.map(norm);

  const merged = [];
  for (const chunk of chunks) {
    const c = norm(chunk);
    // Does this chunk START with a reported fragment? If so, it was wrongly
    // split, so glue it back onto the previous chunk.
    const hit = fragNorms.some(f => f && c.startsWith(f));
    if (hit && merged.length > 0) {
      merged[merged.length - 1] = (merged[merged.length - 1] + " " + chunk).replace(/\s+/g, " ").trim();
    } else {
      merged.push(chunk);
    }
  }
  return merged;
}

// ---------------------------------------------------------------------------
// Main chunker
// ---------------------------------------------------------------------------

function splitIntoChunks(text) {
  const chunks = [];

  // Step 1: Split on |BREAK| markers, then heal conjunction-starting segments
  // back to their predecessor. A line starting with "or stored data." was
  // a new line in the source but belongs to the previous sentence.
  const _HEAL_CONJ = /^\s*(and|but|or|so|yet|nor|for)\b/i;
  const rawSegments = text.split('|BREAK|');
  const segments = [];
  for (const seg of rawSegments) {
    const s = seg.replace(/\s+/g, ' ').trim();
    if (!s) continue;
    if (segments.length > 0 && _HEAL_CONJ.test(s) && s.length <= 60) {
      // Attach to the previous segment, since it's the same sentence just
      // broken across lines
      segments[segments.length - 1] = segments[segments.length - 1].replace(/[.!?]\s*$/, '') + ' ' + s;
    } else {
      segments.push(s);
    }
  }

  for (const seg of segments) {
    if (!seg || (seg.match(/[a-zA-Z]/g) || []).length < 2) continue;

    // Step 2: Split each segment into individual sentences
    const sentences = splitSentences(seg);

    if (sentences.length === 0) continue;

    // Step 3: Each sentence becomes its own chunk.
    // If a sentence is too long, split it on clauses.
    // Never pack two sentences into one chunk, which guarantees that N
    // sentences always gives N chunks.
    for (const raw of sentences) {
      const s = raw.trim();
      if (!s || (s.match(/[a-zA-Z]/g) || []).length < 2) continue;

      if (s.length <= MAX_CHARS) {
        // It fits, so emit it as its own chunk
        if (s.length >= minFor(s)) chunks.push(s);
      } else {
        // Too long, so split on clauses and hard-split any clause still over
        // the cap. Undersized pieces get glued to a neighbour, never dropped
        // (the old code silently discarded short clauses, losing words) and
        // never emitted alone (a fragment like "correct." spoken as its own
        // chunk sounds unnatural).
        const rawPieces = [];
        splitOnClauses(s).forEach(c => {
          const cl = c.trim();
          if (!cl || (cl.match(/[a-zA-Z]/g) || []).length < 2) return;
          if (cl.length <= MAX_CHARS) rawPieces.push(cl);
          else hardSplitAtWord(cl, MAX_CHARS).forEach(p => { const pt = p.trim(); if (pt) rawPieces.push(pt); });
        });
        for (let i = 0; i < rawPieces.length; i++) {
          const piece = rawPieces[i];
          if (piece.length >= minFor(piece)) { chunks.push(piece); continue; }
          if (i + 1 < rawPieces.length) {
            // Prefer gluing forward: the fragment leads into the next clause.
            rawPieces[i + 1] = piece + ' ' + rawPieces[i + 1];
          } else if (chunks.length > 0 && (chunks[chunks.length - 1].length + piece.length + 1) <= MAX_CHARS + 20) {
            // Tail fragment: glue onto the previous chunk (slight cap overshoot
            // is fine; far better than a detached "correct." chunk).
            chunks[chunks.length - 1] = chunks[chunks.length - 1] + ' ' + piece;
          } else {
            chunks.push(piece);   // last resort: keep it. Words are never lost.
          }
        }
      }
    }

    // If segment had no sentence-terminal punctuation (e.g. a heading or label),
    // splitSentences returns the whole segment as one item, which is correct.
  }

  // Merge any chunk that starts with a bare conjunction into its predecessor.
  // These are always orphan fragments left by clause splitting. They sound
  // detached and get "swallowed" because they're too short
  // to register as a complete thought.
  const _CONJ_START = /^(and|but|or|so|yet|nor|for|however|therefore|because)\b/i;
  const merged = [];
  for (const chunk of chunks) {
    if (merged.length > 0 && _CONJ_START.test(chunk) && chunk.length <= 50) {
      merged[merged.length - 1] = merged[merged.length - 1].replace(/[.!?]$/, '') + ' ' + chunk;
    } else {
      merged.push(chunk);
    }
  }

  return merged.length > 0 ? merged : [text.replace(/\|[A-Z/]+\|/g, '').trim().substring(0, MAX_CHARS)];
}


// ---------------------------------------------------------------------------
// Continuation sentence detection
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Sentence splitter
// Built once per call, and ABBREVS is module-level so the Set isn't rebuilt
// ---------------------------------------------------------------------------

const _ABBREVS = new Set([
  'mr','mrs','ms','dr','prof','sr','jr','vs','etc','i.e','e.g','fig',
  'dept','approx','est','inc','ltd','corp','co','no','vol','rev',
  'gen','col','sgt','jan','feb','mar','apr','jun','jul','aug','sep',
  'oct','nov','dec','mon','tue','wed','thu','fri','sat','sun',
  'st','ave','blvd','rd','pt','mt','ft','op','ed','pp','ph',
]);

function splitSentences(text) {
  const results = [];
  let   current = "";

  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    current += ch;

    if (ch !== '.' && ch !== '!' && ch !== '?') continue;

    // Consume full ellipsis as one token
    if (ch === '.' && text[i+1] === '.' && text[i+2] === '.') {
      current += '..';
      i += 2;
      continue;
    }

    // Look ahead past whitespace
    let j = i + 1;
    while (j < text.length && text[j] === ' ') j++;
    const nextChar = text[j] || '';
    const prevWord = current.trim().split(_RX_WHITESPACE).pop().replace(/[.!?]+$/, '').toLowerCase();

    const isDecimal    = ch === '.' && /\d/.test(text[i-1] || '') && /\d/.test(nextChar);
    const isAbbrev     = ch === '.' && (_ABBREVS.has(prevWord) || prevWord.length <= 2);
    const isInitial    = ch === '.' && prevWord.length === 1 && /[a-z]/i.test(prevWord);
    const noCapNext    = nextChar && !/[A-Z"'\u201C\u2018(]/.test(nextChar);
    const isEOT        = j >= text.length;
    // Dotted identifier: "Local.Input", "Upper(Local.Input", "System.User"
    // Extract the last identifier token (after any paren/bracket) and check if
    // it's PascalCase followed by a letter, so property access not a sentence end.
    const _lastIdent = (prevWord.match(/[A-Za-z_][A-Za-z0-9_]*$/) || [''])[0];
    const isDottedPath = ch === '.' && /^[A-Z][a-zA-Z]+$/.test(_lastIdent) && /[a-zA-Z_]/.test(nextChar);

    if (isDecimal || isAbbrev || isInitial || isDottedPath || (noCapNext && !isEOT)) continue;

    const trimmed = current.trim();
    if (isReadable(trimmed)) results.push(trimmed);
    current = "";
  }

  const last = current.trim();
  if (isReadable(last)) results.push(last);
  return results;
}


// ---------------------------------------------------------------------------
// Clause splitter
// ---------------------------------------------------------------------------

function splitOnClauses(text) {
  let parts;

  if (text.includes(';')) {
    parts = text.split(';').map(s => s.trim()).filter(isReadable);
  } else {
    const conjComma = text.split(/,\s*(?=(?:and|but|or|so|yet|although|because|however|therefore|whereas)\b)/i);
    if (conjComma.length > 1) {
      parts = conjComma.map(s => s.trim()).filter(isReadable);
    } else if (text.includes(',')) {
      parts = splitOnCommas(text);
    } else {
      const conjSplit = text.split(/\s+(?=\b(?:and|but|or|so)\b\s+)/i);
      parts = conjSplit.length > 1 ? conjSplit.map(s => s.trim()).filter(isReadable) : [text];
    }
  }

  // Merge orphan conjunction fragments back to their predecessor.
  // e.g. ["agent outputs", "or stored data."] -> ["agent outputs or stored data."]
  // A fragment is an orphan if it starts with a conjunction and is short, so 40
  // characters or fewer.
  const _CONJ = /^(and|but|or|so|yet|nor|for)\b/i;
  const merged = [];
  for (const part of parts) {
    if (merged.length > 0 && _CONJ.test(part) && part.length <= 40) {
      merged[merged.length - 1] = merged[merged.length - 1] + ' ' + part;
    } else {
      merged.push(part);
    }
  }
  return merged.filter(isReadable);
}

function splitOnCommas(text) {
  const parts   = text.split(',');
  const results = [];
  let   current = "";

  for (const part of parts) {
    const candidate = current ? current + ", " + part : part;
    if (candidate.length > TARGET_CHARS && current) {
      results.push(current.trim());
      current = part;
    } else {
      current = candidate;
    }
  }
  if (current.trim()) results.push(current.trim());
  return results;
}


// ---------------------------------------------------------------------------
// Hard word-boundary split (last resort)
// ---------------------------------------------------------------------------

function hardSplitAtWord(text, maxLen) {
  // A tail shorter than this sounds like a detached fragment when spoken alone,
  // so a split that would create one is rebalanced toward the midpoint instead.
  const MIN_TAIL = 30;
  const parts = [];
  let   rem   = text;

  while (rem.length > maxLen) {
    const win        = rem.substring(0, maxLen);
    const punctMatch = win.match(/^[\s\S]*[.!?,]/);
    let   splitAt    = punctMatch && punctMatch[0].length > MIN_CHARS
                       ? punctMatch[0].length
                       : Math.max(win.lastIndexOf(' '), MIN_CHARS);
    // Tail guard: greedy splitting can leave a tiny orphan ("correct.") as the
    // final piece. When the remainder would be under MIN_TAIL, move the split
    // to a word boundary near the midpoint so both halves are natural phrases.
    const tail = rem.length - splitAt;
    if (tail > 0 && tail < MIN_TAIL) {
      const mid  = Math.floor(rem.length / 2);
      const back = rem.lastIndexOf(' ', mid);
      const fwd  = rem.indexOf(' ', mid);
      const cand = (back >= MIN_CHARS) ? back : (fwd > 0 && fwd <= maxLen ? fwd : splitAt);
      if (cand >= MIN_CHARS && cand <= maxLen) splitAt = cand;
    }
    parts.push(rem.substring(0, splitAt).trim());
    rem = rem.substring(splitAt).trim();
  }
  if (rem) parts.push(rem);
  return parts;
}


// ---------------------------------------------------------------------------
// Readability gate
// ---------------------------------------------------------------------------

function isReadable(s) {
  if (!s || s.length < MIN_CHARS) return false;
  return (s.match(/[a-zA-Z]/g) || []).length >= 2;
}


// =============================================================================
// UI HELPERS
// =============================================================================

function renderTextView(chunks, activeIndex) {
  const view = document.getElementById("text-view");
  view.style.display = "block";
  view.innerHTML     = "";
  chunks.forEach((chunk, i) => {
    const div = document.createElement("div");
    div.className = "chunk-item" +
      (i === activeIndex ? " active" : i < activeIndex ? " played" : "");
    div.style.position = "relative";
    div.style.paddingRight = "20px";
    const text = stripMarkersForDisplay(chunk);
    div.textContent = text;
    div.addEventListener("click", () => {
      chrome.runtime.sendMessage({ action: "jumpTo", index: i }).catch(() => {});
    });

    // The flag button, appended to chunk-item so the class styles still apply
    const flagBtn = document.createElement("button");
    flagBtn.textContent = "⚑";
    flagBtn.title = "Report this chunk";
    flagBtn.style.cssText = "position:absolute;top:4px;right:6px;background:transparent;border:none;color:#555;cursor:pointer;font-size:10px;padding:0;line-height:1;transition:color 0.15s;z-index:1";
    flagBtn.addEventListener("mouseenter", () => flagBtn.style.color = "#ef4444");
    flagBtn.addEventListener("mouseleave", () => flagBtn.style.color = "#555");
    flagBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      const base    = chrome.runtime.getURL("player.html");
      const hash    = "#report:" + encodeURIComponent(text);
      // Match player.html regardless of its current hash
      chrome.tabs.query({}, tabs => {
        const existing = tabs.find(t => t.url && t.url.startsWith(base));
        if (existing) {
          // The tab is already open, so I inject the hash through a script and
          // hashchange fires without a full page reload
          chrome.scripting.executeScript({
            target: { tabId: existing.id },
            func: (reportHash) => { window.location.hash = reportHash; },
            args: [hash]
          }).then(() => {
            chrome.tabs.update(existing.id, { active: true });
          }).catch(() => {
            // scripting isn't available, so fall back to updating the URL
            chrome.tabs.update(existing.id, { url: base + hash, active: true });
          });
        } else {
          chrome.tabs.create({ url: base + hash, active: true });
        }
      });
    });
    div.appendChild(flagBtn);
    view.appendChild(div);
  });
  scrollToActive(activeIndex);
}

function updateActiveChunk(index) {
  const view  = document.getElementById("text-view");
  if (!view) return;
  const items = view.querySelectorAll(".chunk-item");
  items.forEach((item, i) => {
    item.classList.remove("active", "played");
    if      (i === index) item.classList.add("active");
    else if (i < index)   item.classList.add("played");
  });
  scrollToActive(index);
}

function scrollToActive(index) {
  const view  = document.getElementById("text-view");
  const items = view.querySelectorAll(".chunk-item");
  if (items[index]) items[index].scrollIntoView({ block: "nearest", behavior: "smooth" });
}

function showPlayer(show) {
  document.getElementById("player-bar").style.display = show ? "block" : "none";
}

function updatePlayerLabel(current, total) {
  document.getElementById("player-label").textContent = `Reading ${current} of ${total}`;
}

function updateProgressFill(current, total) {
  const pct = total > 0 ? (current / total) * 100 : 0;
  document.getElementById("progress-fill").style.width = pct + "%";
}

// =============================================================================
// TEXT EXTRACTION
// =============================================================================
//
// Semantic markers injected into the text stream so server.py can apply
// the correct prosodic treatment to each content type:
//
//   |H1| ... |/H1|            a top-level heading, longest pause either side
//   |H2| ... |/H2|            a section heading
//   |H3| ... |/H3|            a sub-section heading
//   |BOLD| ... |/BOLD|        bold or strong emphasis
//   |ITALIC| ... |/ITALIC|    italic or soft emphasis
//   |CODE| ... |/CODE|        an inline code term
//   |CALLOUT| ... |/CALLOUT|  a note, warning, tip or blockquote
//   |CAPTION| ... |/CAPTION|  a figure or table caption
//   |BREAK|                   a paragraph or block boundary
//
// The server strips the markers once it has used them, so they never reach XTTS.
// =============================================================================

// Wrap a text-extraction promise so it can never hang the UI. If the page does
// not respond in time (navigating, heavy iframes, a frame that never returns),
// resolve with a sentinel the caller turns into a clear message instead of
// leaving the popup stuck on a progress line forever.
function _withExtractionTimeout(promise, ms = 8000) {
  return Promise.race([
    promise,
    new Promise(res => setTimeout(() => res("__KAM_TIMEOUT__"), ms)),
  ]);
}

function getSelectedText() {
  return new Promise((resolve) => {
    chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
      // Guard: extension pages (the KAM dashboard), chrome:// and the Web Store
      // can't be scripted. Without this the call fails with an opaque
      // "Cannot access contents of url" and the button appears to do nothing.
      const _u = (tabs && tabs[0] && tabs[0].url) || "";
      if (!tabs || !tabs[0] || /^(chrome|edge|about|chrome-extension|devtools):/.test(_u)
          || _u.includes("chromewebstore.google.com")) {
        resolve("__KAM_NO_PAGE__");
        return;
      }
      chrome.scripting.executeScript(
        {
          target: { tabId: tabs[0].id, allFrames: true },
          func: () => {
            // Only true kix-canvas Google Docs genuinely can't be selected.
            if (document.querySelector('.kix-canvas-tile-content')) {
              return '__KAM_CANVAS_DOC__';
            }

            const sel = window.getSelection();
            if (!sel || sel.rangeCount === 0) return '';

            const range = sel.getRangeAt(0);

            // Walk every node in the selection using TreeWalker.
            // Inject |BREAK| whenever we cross a block-level element boundary.
            // This works on any site whatever its DOM structure.
            const BLOCK_TAGS = new Set(['p','li','dt','dd','div','section','article',
              'blockquote','h1','h2','h3','h4','h5','h6','td','th','tr',
              'header','footer','main','aside','pre','ul','ol','dl']);
            const INLINE_TAGS = {
              'b': ['|BOLD|','|/BOLD|'], 'strong': ['|BOLD|','|/BOLD|'],
              'i': ['|ITALIC|','|/ITALIC|'], 'em': ['|ITALIC|','|/ITALIC|'],
              'code': ['|CODE|','|/CODE|'], 'kbd': ['|CODE|','|/CODE|'],
              'mark': ['|BOLD|','|/BOLD|']
            };

            const parts = [];
            let   lastWasBlock = false;

            // True if the running output ends with whitespace or an open
            // bracket, meaning a separator is already there and I mustn't add one.
            function _endsClean() {
              for (let k = parts.length - 1; k >= 0; k--) {
                const p = parts[k];
                if (!p) continue;
                const last = p[p.length - 1];
                return /\s/.test(last) || last === '(' || last === '[' || last === undefined;
              }
              return true;   // nothing yet
            }
            // True if a string starts with whitespace or closing punctuation,
            // meaning a separator already exists on that side.
            function _startsClean(s) {
              if (!s) return true;
              return /^[\s.,;:!?)\]}'"]/.test(s);
            }

            // Push a text fragment, preserving its exact content. Inserts a
            // single space only when neither the running output nor the new text
            // already provides a separator, so existing punctuation and
            // spacing (". ", ")", "training. However") is never lost or merged.
            function _pushText(t) {
              if (!t) return;
              if (parts.length && !_endsClean() && !_startsClean(t)) {
                parts.push(' ');
              }
              parts.push(t);
              lastWasBlock = false;
            }

            // Simpler approach: clone the fragment and walk it
            const frag = range.cloneContents();

            function walk(node) {
              if (node.nodeType === Node.TEXT_NODE) {
                // Preserve the node's text verbatim (including any leading/
                // trailing whitespace the page author put there); only collapse
                // runs of whitespace, never strip edge characters.
                const t = node.textContent.replace(/[ \t\r\n]+/g, ' ');
                _pushText(t);
                return;
              }
              const tag = node.nodeName.toLowerCase();

              // --- Equations ---
              // MathML / MathJax / KaTeX render equations as nested glyph
              // elements (MathJax often into <svg>), so naively walking them
              // gives garbled text, and the hidden source copy then gets read a
              // second time. So I intercept the container and emit clean source
              // just once.
              const isMathRoot = (
                tag === 'math' || tag === 'mjx-container' ||
                (node.classList && (node.classList.contains('katex') ||
                                    node.classList.contains('MathJax')))
              );
              if (isMathRoot) {
                let eq = '';
                try {
                  // 1. The LaTeX source, which is the most faithful, and both
                  //    MathJax and KaTeX embed it.
                  const ann = node.querySelector &&
                    node.querySelector('annotation[encoding="application/x-tex"]');
                  if (ann && ann.textContent.trim()) eq = ann.textContent.trim();
                  // 2. Accessibility text set by the renderer.
                  if (!eq && node.getAttribute) {
                    eq = (node.getAttribute('alttext') ||
                          node.getAttribute('aria-label') || '').trim();
                  }
                  // 3. Fall back to visible text, minus the hidden source copy.
                  if (!eq && node.cloneNode) {
                    const c = node.cloneNode(true);
                    c.querySelectorAll(
                      'annotation, annotation-xml, mjx-assistive-mml, .katex-mathml'
                    ).forEach(n => n.remove());
                    eq = (c.textContent || '').replace(/\s+/g, ' ').trim();
                  }
                } catch (e) { /* fall through to empty */ }
                if (eq) _pushText(' ' + eq + ' ');
                return;   // never walk into the equation's internals
              }
              // Skip hidden equation-source duplicates encountered on their own.
              if (['annotation', 'annotation-xml'].includes(tag)) return;
              if (node.classList && (node.classList.contains('katex-mathml') ||
                  tag === 'mjx-assistive-mml')) return;

              // Heading → inject level marker + breaks
              if (['h1','h2','h3','h4','h5','h6'].includes(tag)) {
                if (!lastWasBlock) parts.push(' |BREAK| ');
                const level = tag === 'h1' ? 'H1' : tag === 'h2' ? 'H2' : 'H3';
                parts.push('|' + level + '|');
                Array.from(node.childNodes).forEach(walk);
                parts.push('|/' + level + '| |BREAK| ');
                lastWasBlock = true;
                return;
              }

              // Inline semantic markers
              if (INLINE_TAGS[tag]) {
                parts.push(' ' + INLINE_TAGS[tag][0]);
                Array.from(node.childNodes).forEach(walk);
                parts.push(INLINE_TAGS[tag][1] + ' ');
                return;
              }

              // Block elements → inject |BREAK| before and after
              if (BLOCK_TAGS.has(tag)) {
                if (parts.length > 0 && !lastWasBlock) parts.push(' |BREAK| ');
                Array.from(node.childNodes).forEach(walk);
                parts.push(' |BREAK| ');
                lastWasBlock = true;
                return;
              }

              // Everything else, so span, a and the rest, gets recursed into.
              // Punctuation sitting outside the element, like "(<a>2024</a>)" or
              // "<a>x</a>. Next", is
              // in sibling text nodes and is preserved by _pushText's boundary
              // logic, so citations and sentence-final stops survive intact.
              Array.from(node.childNodes).forEach(walk);
            }

            Array.from(frag.childNodes).forEach(walk);

            let text = parts.join('')
              .replace(/(\|BREAK\|\s*){2,}/g, ' |BREAK| ')
              // Collapse only spaces and tabs, not punctuation, so ". However"
              // survives.
              .replace(/[ \t]{2,}/g, ' ')
              .replace(/\s+/g, ' ')
              .trim();

            // If we got nothing useful from DOM walk (e.g. plain text selection),
            // fall back to raw selection string and split on newlines
            if (!text || text.replace(/\|BREAK\|/g, '').trim().length < 5) {
              text = sel.toString()
                .replace(/\r\n|\n/g, ' |BREAK| ')
                .replace(/(\|BREAK\|\s*){2,}/g, ' |BREAK| ')
                .replace(/\s+/g, ' ')
                .trim();
            }

            return text;
          }
        },
        (results) => {
          if (chrome.runtime.lastError) {
            showError("Can't read this page: " + chrome.runtime.lastError.message
                      + " — try reloading the page, or use Custom Text.");
            resolve("");
            return;
          }
          const vals = (results || []).map(r => r && r.result);
          if (vals.includes('__KAM_CANVAS_DOC__') && !vals.some(v => typeof v === 'string' && v && v !== '__KAM_CANVAS_DOC__')) {
            showError("This looks like a Google Doc — its text is drawn on a canvas and can't be selected directly. Copy the text (Ctrl+C), switch to the Custom Text tab, and paste it there to read it.");
            resolve("");
            return;
          }
          // The frame with the selection is the one returning non-empty text.
          const r = vals.filter(v => typeof v === 'string' && v && v !== '__KAM_CANVAS_DOC__')
                        .sort((a, b) => b.length - a.length)[0] || "";
          if (!r) showError("Select some text on the page first, then press Speak.");
          resolve(r);
        }
      );
    });
  });
}

function getPageText() {
  return new Promise((resolve) => {
    chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
      // Guard: extension pages (the KAM dashboard), chrome:// and the Web Store
      // can't be scripted. Without this the call fails with an opaque
      // "Cannot access contents of url" and the button appears to do nothing.
      const _u = (tabs && tabs[0] && tabs[0].url) || "";
      if (!tabs || !tabs[0] || /^(chrome|edge|about|chrome-extension|devtools):/.test(_u)
          || _u.includes("chromewebstore.google.com")) {
        resolve("__KAM_NO_PAGE__");
        return;
      }
      chrome.scripting.executeScript(
        {
          target: { tabId: tabs[0].id, allFrames: true },
          func: () => {
            // Only true canvas-rendered Google Docs (kix) genuinely can't be
            // read; signal that. Plain skills.google / iframe content is read
            // normally below. I no longer block by hostname, since a lot of
            // those pages keep the real text in an iframe that allFrames reaches.
            if (document.querySelector('.kix-canvas-tile-content')) {
              return '__KAM_CANVAS_DOC__';
            }
            // Block tags that create chunk boundaries
            const BLOCK = new Set(['p','li','dt','dd','blockquote','pre',
              'h1','h2','h3','h4','h5','h6','td','th','tr','section',
              'article','aside','div','main','header','footer']);
            const SKIP  = new Set(['script','style','noscript','nav','footer',
              'header','aside','iframe','svg','img','button','input','select',
              'textarea','form','[aria-hidden]']);
            const INLINE_MAP = {
              'b':'BOLD','strong':'BOLD','em':'ITALIC','i':'ITALIC',
              'code':'CODE','kbd':'CODE','mark':'BOLD','samp':'CODE'
            };

            // Find best content root
            const root =
              document.querySelector('article') ||
              document.querySelector('main')    ||
              document.querySelector("[role='main']") ||
              document.querySelector('.content') ||
              document.querySelector('#content') ||
              document.body;

            const parts = [];
            let lastWasBlock = false;

            function shouldSkip(el) {
              if (!el || el.nodeType !== Node.ELEMENT_NODE) return false;
              const tag = el.tagName.toLowerCase();
              if (SKIP.has(tag)) return true;
              const style = window.getComputedStyle(el);
              if (style.display === 'none' || style.visibility === 'hidden') return true;
              if (el.getAttribute('aria-hidden') === 'true') return true;
              if (el.getAttribute('hidden') !== null) return true;
              // Skip nav/menu by class
              const cls = (el.className || '').toString();
              if (/\b(nav|navbar|menu|sidebar|footer|header|ad|cookie|popup|modal|sr-only|visually-hidden)\b/i.test(cls)) return true;
              return false;
            }

            function walk(node) {
              if (node.nodeType === Node.TEXT_NODE) {
                const t = (node.textContent || '').replace(/\s+/g, ' ');
                if (t.trim()) { parts.push(t); lastWasBlock = false; }
                return;
              }
              if (node.nodeType !== Node.ELEMENT_NODE) return;
              if (shouldSkip(node)) return;

              const tag = node.tagName.toLowerCase();

              // Headings
              if (['h1','h2','h3','h4','h5','h6'].includes(tag)) {
                const t = (node.textContent || '').trim();
                if (!t) return;
                if (!lastWasBlock) parts.push(' |BREAK| ');
                const level = tag === 'h1' ? 'H1' : tag === 'h2' ? 'H2' : 'H3';
                parts.push('|' + level + '|' + t + '.|/' + level + '| |BREAK| ');
                lastWasBlock = true;
                return;
              }

              // Inline semantic markers
              if (INLINE_MAP[tag]) {
                const t = (node.textContent || '').trim();
                if (t) parts.push(' |' + INLINE_MAP[tag] + '|' + t + '|/' + INLINE_MAP[tag] + '| ');
                return;
              }

              // Code blocks get skipped, since they're too noisy for TTS
              if (tag === 'pre') return;

              // Block elements, where I inject the break boundaries
              if (BLOCK.has(tag)) {
                const hadContent = parts.length;
                if (!lastWasBlock && parts.length > 0) parts.push(' |BREAK| ');
                Array.from(node.childNodes).forEach(walk);
                if (parts.length > hadContent) {
                  parts.push(' |BREAK| ');
                  lastWasBlock = true;
                }
                return;
              }

              // Everything else gets recursed into
              Array.from(node.childNodes).forEach(walk);
            }

            Array.from(root.childNodes).forEach(walk);

            let text = parts.join('')
              // Clean nav noise
              .replace(/[Ll]inks?\s+to\s+(an?\s+)?(external\s+site|pdf|document|page)/g, '')
              .replace(/opens?\s+in\s+(a\s+)?new\s+(tab|window)/gi, '')
              .replace(/external\s+link/gi, '')
              .replace(/\bPrevious\b|\bNext\b/g, '')
              .replace(/\bback\s+to\s+top\b/gi, '')
              .replace(/\bread\s+more\b|\blearn\s+more\b|\bsee\s+more\b/gi, '')
              .replace(/https?:\/\/\S+/g, '')
              .replace(/\[\d+\]/g, '')
              // Symbol conversion
              .replace(/!=/g,' not equals ')
              .replace(/>=/g,' greater than or equal to ')
              .replace(/<=/g,' less than or equal to ')
              .replace(/->/g,' arrow ')
              .replace(/=>/g,' arrow ')
              .replace(/&&/g,' and ')
              // Collapse
              .replace(/(\|BREAK\|\s*){2,}/g, ' |BREAK| ')
              .replace(/\s+/g, ' ')
              .trim();

            return text;
          }
        },
        (results) => {
          // A genuine injection failure must not look like "no text found".
          if (chrome.runtime.lastError) {
            showError("Can't read this page: " + chrome.runtime.lastError.message
                      + " — try reloading the page, or use Custom Text.");
            resolve("");
            return;
          }
          // allFrames returns one result per frame, so I pick the richest text,
          // which is the content iframe rather than the top-page header.
          const texts = (results || [])
            .map(r => r && r.result)
            .filter(t => typeof t === 'string' && t !== '__KAM_CANVAS_DOC__');
          const best = texts.sort((a, b) => b.length - a.length)[0] || "";
          const onlyCanvas = !best && (results || []).some(r => r && r.result === '__KAM_CANVAS_DOC__');
          if (onlyCanvas) {
            showError("This looks like a Google Doc — its text is drawn on a canvas and can't be read directly. Copy the text (Ctrl+C), switch to the Custom Text tab, and paste it there.");
            resolve("");
            return;
          }
          if (!best) showError("Page text extraction failed — try again.");
          resolve(best);
        }
      );
    });
  });
}

function showError(msg) {
  const el = document.getElementById("error-msg");
  el.textContent   = "⚠ " + msg;
  el.style.background = "#1a0a0a";
  el.style.borderColor = "#3a1a1a";
  el.style.color   = "#f87171";
  el.style.display = "block";
}

function showInfo(msg) {
  const el = document.getElementById("error-msg");
  el.textContent   = "ℹ " + msg;
  el.style.background = "#0a1a1a";
  el.style.borderColor = "#1a3a3a";
  el.style.color   = "#67e8f9";
  el.style.display = "block";
}

function hideError() {
  document.getElementById("error-msg").style.display = "none";
}
