#!/usr/bin/env python3
"""
KAM TTS — Native Messaging Host
================================

Chrome extensions cannot launch a local process directly. This tiny host is the
bridge: Chrome talks to it over stdin/stdout using the native-messaging protocol
(each message = 4-byte little-endian length prefix + UTF-8 JSON), and the host
starts/stops `server.py` and streams its console output back to the dashboard.

Protocol with the extension
---------------------------
Extension → host:
    {"cmd": "start"}      launch server.py (no-op if already running)
    {"cmd": "stop"}       terminate the running server
    {"cmd": "status"}     report whether the server is running
    {"cmd": "ping"}       liveness check

Host → extension (may be many):
    {"type": "status",  "running": bool, "pid": int|null}
    {"type": "log",     "line": "<stdout line>"}
    {"type": "ready"}                      emitted when server prints its ready marker
    {"type": "exit",    "code": int}       server process ended
    {"type": "error",   "message": "..."}

Setup is one-time via register_host.py (writes the host manifest + a registry
key so Chrome trusts this host for the KAM extension ID).
"""
import sys
import os
import json
import struct
import threading
import subprocess
import urllib.request as _urlreq

# Per-install local API token, used for the graceful /shutdown call.
# Generated by server.py on first run (kam_token.txt); KAM_TOKEN env overrides.
def _read_token():
    """Per-install token written by the server (kam_token.txt); env overrides."""
    env = os.environ.get("KAM_TOKEN")
    if env:
        return env.strip()
    try:
        # Resolve the folder locally so this never depends on definition order.
        _here = os.path.dirname(os.path.abspath(__file__))
        with open(os.path.join(_here, "kam_token.txt")) as f:
            return f.read().strip()
    except OSError:
        return ""

KAM_TOKEN = _read_token()

# ── Locate server.py ─────────────────────────────────────────────────────────
# The server lives next to this host file. Override with KAM_SERVER_PY if needed.
HERE = os.path.dirname(os.path.abspath(__file__))
SERVER_PY = os.environ.get("KAM_SERVER_PY", os.path.join(HERE, "server.py"))
PYTHON = os.environ.get("KAM_PYTHON", sys.executable)

# The line server.py prints once warmup is done and it can serve requests.
# Matching is substring + case-insensitive so minor wording changes still work.
READY_MARKERS = ("model ready", "serving on", "running on", "warmup complete")

from typing import Optional
_proc: "Optional[subprocess.Popen]" = None
_proc_lock = threading.Lock()
_log_fh = None   # file handle the child writes stdout/stderr to
_log_path = None # path of kam_server.log


# ── Native messaging framing ─────────────────────────────────────────────────
def _read_message():
    """Read one message from stdin, or None on EOF."""
    raw_len = sys.stdin.buffer.read(4)
    if len(raw_len) < 4:
        return None
    msg_len = struct.unpack("=I", raw_len)[0]
    data = sys.stdin.buffer.read(msg_len)
    if len(data) < msg_len:
        return None
    try:
        return json.loads(data.decode("utf-8"))
    except Exception:
        return None


_send_lock = threading.Lock()


def _send(obj):
    """Write one message to stdout. Thread-safe (the reader thread also sends)."""
    data = json.dumps(obj).encode("utf-8")
    with _send_lock:
        try:
            sys.stdout.buffer.write(struct.pack("=I", len(data)))
            sys.stdout.buffer.write(data)
            sys.stdout.buffer.flush()
        except Exception:
            pass


# ── Server process management ────────────────────────────────────────────────
def _is_running():
    return _proc is not None and _proc.poll() is None


def _pipe_reader(proc):
    """Tail the child's log file and stream new lines to the dashboard. Readiness
    is driven by the .kam_ready sentinel file (buffering-proof), with the printed
    marker as a backup. Startup progress is surfaced from the .kam_stage file."""
    import time
    state = {"ready": False, "lines": 0, "last": time.time(), "start": time.time(), "stage": ""}
    base = os.path.dirname(SERVER_PY) or HERE
    sentinel = os.path.join(base, ".kam_ready")
    stage_file = os.path.join(base, ".kam_stage")
    log_path = _log_path or os.path.join(base, "kam_server.log")
    pos = 0

    def _mark_ready(reason):
        if not state["ready"]:
            state["ready"] = True
            _send({"type": "log", "line": f"[HOST] ✓ Model Ready ({reason})"})
            _send({"type": "ready"})

    try:
        while True:
            alive = proc.poll() is None
            # 1) readiness via sentinel file (primary, buffering-proof)
            if not state["ready"] and os.path.exists(sentinel):
                _mark_ready("server ready")
            # 2) mirror any new log lines to the dashboard
            try:
                with open(log_path, "r", encoding="utf-8", errors="replace") as fh:
                    fh.seek(pos)
                    chunk = fh.read()
                    pos = fh.tell()
            except Exception:
                chunk = ""
            if chunk:
                for text in chunk.splitlines():
                    if not text.strip():
                        continue
                    state["lines"] += 1
                    # Forward server output to the dashboard ONLY until it's
                    # ready. After that the dashboard's own /console HTTP poll is
                    # the single source of log lines — forwarding here too would
                    # show every line twice (the duplication bug). We still scan
                    # for the ready marker as a backup to the sentinel file.
                    if not state["ready"]:
                        _send({"type": "log", "line": text})
                        if any(m in text.lower() for m in READY_MARKERS):
                            _mark_ready("startup log")
                state["last"] = time.time()
            # 2b) emit stage changes for the progress bar (every loop, cheap)
            try:
                if os.path.exists(stage_file):
                    with open(stage_file) as _sf:
                        cur_stage = _sf.read().strip()
                    if cur_stage and cur_stage != state.get("stage"):
                        state["stage"] = cur_stage
                        _send({"type": "stage", "stage": cur_stage})
            except Exception:
                pass
            # 3) heartbeat while still loading (no spam — shows current stage)
            if alive and not state["ready"] and time.time() - state["last"] > 15:
                elapsed = int(time.time() - state["start"])
                stg = (" · stage: " + state["stage"]) if state.get("stage") else ""
                _send({"type": "log", "line": f"[HOST] still loading… {elapsed}s elapsed{stg}"})
                state["last"] = time.time()
            # exit once the process is gone and we've drained the log
            if not alive and not chunk:
                # one final readiness check in case it wrote the sentinel late
                if not state["ready"] and os.path.exists(sentinel):
                    _mark_ready("server ready")
                break
            time.sleep(0.4)
    except Exception as e:
        _send({"type": "error", "message": f"reader error: {e}"})
    finally:
        code = proc.poll()
        if not state["ready"]:
            last_stage = ""
            try:
                if os.path.exists(stage_file):
                    with open(stage_file) as _sf:
                        last_stage = _sf.read().strip()
            except Exception:
                pass
            _send({"type": "error", "message":
                   f"Server stopped before ready (exit {code})." +
                   (f" Last stage reached: {last_stage}." if last_stage else
                    " No stage recorded — process never ran.")})
        _send({"type": "exit", "code": code if code is not None else -1})
        _send({"type": "status", "running": False, "pid": None})


def _start():
    global _proc
    with _proc_lock:
        if _is_running() and _proc is not None:
            _send({"type": "status", "running": True, "pid": _proc.pid})
            _send({"type": "log", "line": "[HOST] Server already running."})
            return
        if not os.path.exists(SERVER_PY):
            _send({"type": "error", "message": f"server.py not found at {SERVER_PY}"})
            return
        # If something is already serving on 5050 (e.g. a PowerShell-started
        # server, or a prior launch), don't spawn a second one — that caused
        # double model-loads and frozen playback. Just report it as running.
        import socket as _sk
        _p = _sk.socket(_sk.AF_INET, _sk.SOCK_STREAM); _p.settimeout(0.4)
        try:
            if _p.connect_ex(("127.0.0.1", 5050)) == 0:
                _send({"type": "log", "line": "[HOST] A server is already running on 5050 — using it."})
                _send({"type": "ready"})
                _p.close()
                return
        except Exception:
            pass
        finally:
            _p.close()
        try:
            child_env = dict(os.environ)
            child_env["PYTHONUNBUFFERED"] = "1"
            child_env["PYTHONIOENCODING"] = "utf-8"
            child_env["KAM_LAUNCHED_BY_HOST"] = "1"

            global _log_path, _log_fh
            base_dir = os.path.dirname(SERVER_PY) or HERE
            _log_path = os.path.join(base_dir, "kam_server.log")
            # Clear stale readiness/stage/lock files BEFORE launching.
            for _stale in (".kam_ready", ".kam_stage", ".kam_lock"):
                try:
                    _p = os.path.join(base_dir, _stale)
                    if os.path.exists(_p):
                        os.remove(_p)
                except Exception:
                    pass
            # Open the log file and hand it to the child as stdout/stderr.
            # subprocess.Popen makes this handle inheritable correctly on Windows
            # (via STARTUPINFO) — no cmd.exe and no quoting games (our paths have
            # spaces, which the cmd `/c "…"` form mangles). This is the simple,
            # correct launch: same as PowerShell `python -u server.py > log`.
            _log_fh = open(_log_path, "w", encoding="utf-8", buffering=1)
            _log_fh.write("[HOST] ---- launching, server output follows ----\n")
            _log_fh.flush()
            creationflags = getattr(subprocess, "CREATE_NO_WINDOW", 0) if os.name == "nt" else 0
            _proc = subprocess.Popen(
                [PYTHON, "-u", SERVER_PY],
                stdout=_log_fh,
                stderr=subprocess.STDOUT,
                stdin=subprocess.DEVNULL,
                cwd=base_dir,
                env=child_env,
                creationflags=creationflags,
            )
        except Exception as e:
            _send({"type": "error", "message": f"failed to launch: {e}"})
            return
        _send({"type": "status", "running": True, "pid": _proc.pid})
        _send({"type": "log", "line": f"[HOST] Launched server.py (pid {_proc.pid})"})
        _send({"type": "log", "line": f"[HOST] Python: {PYTHON}"})
        _send({"type": "log", "line": f"[HOST] Working dir: {base_dir}"})
        _send({"type": "log", "line": "[HOST] Waiting for server output…"})
        threading.Thread(target=_pipe_reader, args=(_proc,), daemon=True).start()


def _stop():
    global _proc
    with _proc_lock:
        if not _is_running() or _proc is None:
            _send({"type": "status", "running": False, "pid": None})
            return
        proc = _proc  # local non-None binding for the type checker
        pid = proc.pid
        # Graceful first: ask the server to finish its current chunk and exit
        # cleanly (no mid-synthesis kill, no mid-write database risk). Fall back
        # to terminate/kill only if it doesn't exit in time.
        graceful = False
        try:
            req = _urlreq.Request(
                "http://127.0.0.1:5050/shutdown", data=b"{}", method="POST",
                headers={"Content-Type": "application/json", "X-KAM-Token": KAM_TOKEN or _read_token()},
            )
            _urlreq.urlopen(req, timeout=2)
            try:
                proc.wait(timeout=18)   # synthesis can hold the lock up to 15s
                graceful = True
            except subprocess.TimeoutExpired:
                pass
        except Exception:
            pass
        if not graceful:
            try:
                proc.terminate()
                try:
                    proc.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    proc.kill()
            except Exception as e:
                _send({"type": "error", "message": f"stop error: {e}"})
        # Remove readiness/stage/lock files so the next launch starts clean.
        base = os.path.dirname(SERVER_PY) or HERE
        for _f in (".kam_ready", ".kam_stage", ".kam_lock"):
            try:
                _pp = os.path.join(base, _f)
                if os.path.exists(_pp):
                    os.remove(_pp)
            except Exception:
                pass
        _send({"type": "log", "line": f"[HOST] Stopped server (pid {pid})"})
        _send({"type": "status", "running": False, "pid": None})
        _proc = None


def main():
    while True:
        msg = _read_message()
        if msg is None:
            break  # Chrome closed the port → exit host
        cmd = (msg or {}).get("cmd")
        if cmd == "start":
            _start()
        elif cmd == "stop":
            _stop()
        elif cmd == "status":
            running = _is_running()
            _send({"type": "status", "running": running,
                   "pid": _proc.pid if (running and _proc is not None) else None})
        elif cmd == "ping":
            _send({"type": "pong"})
        else:
            _send({"type": "error", "message": f"unknown cmd: {cmd}"})
    # stdin closed: clean up the child so we don't leave an orphan server.
    _stop()


if __name__ == "__main__":
    main()