#!/usr/bin/env python3
"""
KAM TTS — Native Messaging Host registration (one-time setup)
=============================================================

Run this ONCE so Chrome trusts the KAM host. It:
  1. On Windows, compiles a tiny launcher (kam_host.exe) that runs kam_host.py
     with the right Python, using the C# compiler every Windows already ships.
     Chrome 113 and later invoke native hosts as executables directly rather
     than through cmd.exe, and a .bat registered the old way now fails with
     "Specified native messaging host not found", so the launcher has to be a
     real .exe. The generated source is kept beside it so you can read exactly
     what was built.
  2. Writes the native-messaging host manifest (com.kam.tts.json) next to the
     host, pointing at that launcher.
  3. Registers it with Chrome:
       • Windows: a registry key under
         HKCU\\Software\\Google\\Chrome\\NativeMessagingHosts\\com.kam.tts
       • macOS/Linux: drops the manifest into Chrome's NativeMessagingHosts dir.

Usage:
    python register_host.py

manifest.json pins a public key, so Chrome gives the extension the same id on
every machine and there is nothing to look up. Only pass an id if you replaced
that key with your own:

    python register_host.py <EXTENSION_ID>

Find <EXTENSION_ID> at chrome://extensions (toggle Developer mode) — it's the
long id under "KAM TTS". It is also the host segment of the dashboard URL:
chrome-extension://<EXTENSION_ID>/player.html

To unregister:
    python register_host.py --remove
"""
import sys
import os
import json
import re
import stat

# Same guard as the other entry points: a legacy Windows codepage turns any
# non-ASCII character into a UnicodeEncodeError, and the help text below has
# em-dashes in it, so this has to run before the first print.
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

HOST_NAME = "com.kam.tts"

# Extension ids are always 32 letters in a-p. Worth checking, since a typo here
# registers a host that nothing can talk to, and the failure only shows up much
# later as the power button doing nothing.
_EXT_ID_RE = re.compile(r"^[a-p]{32}$")

# manifest.json pins a public key, so Chrome derives the id from that rather
# than from the folder it was loaded from. That makes the id the same on every
# machine, which is why this can be a default instead of something everyone has
# to look up. Only differs if you replaced the key with your own.
PINNED_EXTENSION_ID = "mdhbimlofbadmgombcdmnmnebgglalob"
HERE = os.path.dirname(os.path.abspath(__file__))
HOST_SCRIPT = os.path.join(HERE, "kam_host.py")
MANIFEST_PATH = os.path.join(HERE, f"{HOST_NAME}.json")


def _python_exe():
    """Absolute path to the interpreter running this script, so the
    native-messaging manifest points at the same Python the server uses."""
    return sys.executable or "python"


LAUNCHER_EXE = os.path.join(HERE, "kam_host.exe")
LAUNCHER_SRC = os.path.join(HERE, "kam_host_launcher.cs")
LAUNCHER_BAT = os.path.join(HERE, "kam_host.bat")


def _find_csc():
    """The C# compiler that ships inside the .NET Framework on every Windows
    install, so nothing has to be downloaded to build the launcher. 64-bit
    first, then the 32-bit tree, since either produces the same AnyCPU exe."""
    windir = os.environ.get("WINDIR", r"C:\Windows")
    for tree in ("Framework64", "Framework"):
        p = os.path.join(windir, "Microsoft.NET", tree, "v4.0.30319", "csc.exe")
        if os.path.exists(p):
            return p
    return None


def _cs_verbatim(s):
    """Quote a path for a C# @"..." string, where the only escape is a doubled
    quote. Backslashes are literal in verbatim strings, which is the point."""
    return '@"' + s.replace('"', '""') + '"'


def _launcher_source(py):
    """The launcher, with the interpreter and host paths baked in.

    It relays stdin and stdout byte for byte rather than letting the child
    inherit them. Chrome hands the host pipes, not a console, and a process
    started with plain inheritance in that situation comes up with no usable
    standard handles at all: the first version of this did exactly that and
    relayed nothing, which is why the ping test below exists. Closing our stdin
    closes the child's, and stdin closing is the signal kam_host.py already
    exits on, so a launcher Chrome kills takes the host down with it and leaves
    no orphan."""
    return f"""// Generated by register_host.py. Do not edit; re-run register_host.py instead.
// Runs kam_host.py under the Python that has torch installed, relaying the
// native-messaging byte stream both ways. See register_host.py for why this is
// an .exe and not a .bat.
using System;
using System.Diagnostics;
using System.IO;
using System.Threading;
class KamHostLauncher {{
    const string PY   = {_cs_verbatim(py)};
    const string HOST = {_cs_verbatim(HOST_SCRIPT)};
    static void Pump(Stream from, Stream to) {{
        var buf = new byte[65536]; int n;
        try {{ while ((n = from.Read(buf, 0, buf.Length)) > 0) {{ to.Write(buf, 0, n); to.Flush(); }} }}
        catch (Exception) {{ }}
    }}
    static int Main(string[] args) {{
        var extra = "";
        foreach (var a in args) extra += " \\"" + a.Replace("\\"", "\\\\\\"") + "\\"";
        var psi = new ProcessStartInfo(PY, "\\"" + HOST + "\\"" + extra) {{
            UseShellExecute = false, CreateNoWindow = true,
            RedirectStandardInput = true, RedirectStandardOutput = true,
            WorkingDirectory = Path.GetDirectoryName(HOST)
        }};
        psi.EnvironmentVariables["KAM_PYTHON"] = PY;
        using (var p = Process.Start(psi)) {{
            var inPump = new Thread(() => {{
                Pump(Console.OpenStandardInput(), p.StandardInput.BaseStream);
                try {{ p.StandardInput.Close(); }} catch (Exception) {{ }}
            }}) {{ IsBackground = true }};
            var outPump = new Thread(() => Pump(p.StandardOutput.BaseStream, Console.OpenStandardOutput())) {{ IsBackground = true }};
            inPump.Start(); outPump.Start();
            p.WaitForExit();
            outPump.Join(2000);
            return p.ExitCode;
        }}
    }}
}}
"""


def _self_test(exe):
    """Prove the launcher relays the protocol before anything is registered.

    Sends one framed ping the way Chrome would and waits for the framed pong.
    A launcher that compiles but relays nothing is worse than an error, since
    the failure would only show up later as the power button doing nothing, so
    this is not optional."""
    import struct
    import subprocess
    import threading
    msg = json.dumps({"cmd": "ping"}).encode()
    frame = struct.pack("<I", len(msg)) + msg
    try:
        p = subprocess.Popen([exe, f"chrome-extension://{PINNED_EXTENSION_ID}/"],
                             stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                             stderr=subprocess.DEVNULL,
                             creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
    except OSError as e:
        print(f"[ERROR] launcher would not start: {e}")
        return False
    got = {}

    def _read():
        hdr = p.stdout.read(4)
        if len(hdr) == 4:
            got["reply"] = p.stdout.read(struct.unpack("<I", hdr)[0])

    t = threading.Thread(target=_read, daemon=True)
    t.start()
    try:
        p.stdin.write(frame)
        p.stdin.flush()
    except OSError:
        pass
    t.join(10)
    try:
        p.stdin.close()
        p.wait(timeout=6)
    except Exception:
        try:
            subprocess.run(["taskkill", "/PID", str(p.pid), "/T", "/F"],
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except Exception:
            pass
    return b'"pong"' in got.get("reply", b"")


def _write_launcher_bat(py):
    """The old wrapper, kept only as the fallback for a Windows with no C#
    compiler, which should not exist. Written with newline="" because a text
    mode file turns the explicit \\r\\n into \\r\\r\\n, which cmd tolerates but
    nothing else should have to."""
    with open(LAUNCHER_BAT, "w", newline="") as f:
        f.write(f'@echo off\r\nset "KAM_PYTHON={py}"\r\n"{py}" "{HOST_SCRIPT}" %*\r\n')
    return LAUNCHER_BAT


def _write_launcher_windows(python_exe=None):
    """On Windows the manifest 'path' must point at an executable, and since
    Chrome 113 it has to be a real one: hosts are invoked directly rather than
    through cmd.exe, and a .bat registered the old way fails with "Specified
    native messaging host not found" even though every file and registry key
    is exactly where it should be. So the launcher is compiled here, with the
    compiler Windows already has.

    CRITICAL: the interpreter baked in must be the SAME Python that has
    torch/TTS installed and runs your server, otherwise the server crashes on
    import. Defaults to the Python running this script. Returns the launcher
    path, or None if a launcher could be built but does not work, in which case
    nothing should be registered."""
    import subprocess
    py = python_exe or _python_exe()
    csc = _find_csc()
    if not csc:
        print("[WARN] No C# compiler found in the .NET Framework directory, so the")
        print("       launcher is a .bat. Chrome 113 and later may refuse it.")
        return _write_launcher_bat(py)

    with open(LAUNCHER_SRC, "w", encoding="utf-8") as f:
        f.write(_launcher_source(py))
    for stale in (LAUNCHER_EXE, LAUNCHER_BAT):
        try:
            os.remove(stale)
        except OSError:
            pass
    r = subprocess.run([csc, "-nologo", "-optimize+", "-target:exe",
                        f"-out:{LAUNCHER_EXE}", LAUNCHER_SRC],
                       capture_output=True, text=True, cwd=HERE)
    if r.returncode != 0 or not os.path.exists(LAUNCHER_EXE):
        print("[ERROR] The launcher did not compile:")
        print((r.stdout + r.stderr).strip())
        print("        Falling back to a .bat, which Chrome 113 and later may refuse.")
        return _write_launcher_bat(py)

    if not _self_test(LAUNCHER_EXE):
        print("[ERROR] The launcher compiled but did not relay a ping to kam_host.py.")
        print(f"        Interpreter: {py}")
        print("        Check that path runs kam_host.py by hand before registering.")
        return None
    print(f"[OK] Built and tested the launcher: {LAUNCHER_EXE}")
    return LAUNCHER_EXE


def _write_manifest(ext_id, exec_path):
    """Write the Chrome native-messaging manifest for this machine.
    Regenerated per install (absolute paths + extension ID), which is why
    com.kam.tts.json is gitignored rather than committed."""
    manifest = {
        "name": HOST_NAME,
        "description": "KAM TTS server launcher",
        "path": exec_path,
        "type": "stdio",
        "allowed_origins": [f"chrome-extension://{ext_id}/"],
    }
    with open(MANIFEST_PATH, "w") as f:
        json.dump(manifest, f, indent=2)
    return MANIFEST_PATH


def register(ext_id, python_exe=None):
    """Install the native-messaging host so the dashboard power button can
    start and stop the server. Writes the manifest and registers it with Chrome."""
    if os.name == "nt":
        exec_path = _write_launcher_windows(python_exe)
        if not exec_path:
            # Registering a launcher that does not relay would only move the
            # failure to the power button, where it is far harder to see.
            print("[ERROR] Not registered. Fix the launcher first, then re-run.")
            return False
    else:
        # POSIX: make the host directly executable.
        os.chmod(HOST_SCRIPT, os.stat(HOST_SCRIPT).st_mode | stat.S_IEXEC)
        exec_path = HOST_SCRIPT
    _write_manifest(ext_id, exec_path)

    if os.name == "nt":
        import winreg
        key_path = rf"Software\Google\Chrome\NativeMessagingHosts\{HOST_NAME}"
        with winreg.CreateKey(winreg.HKEY_CURRENT_USER, key_path) as key:
            winreg.SetValueEx(key, "", 0, winreg.REG_SZ, MANIFEST_PATH)
        print(f"[OK] Registered (registry) for extension {ext_id}")
        print(f"     Manifest: {MANIFEST_PATH}")
        print(f"     Launcher: {exec_path}")
    else:
        # Chrome looks in a per-user dir; copy the manifest there.
        if sys.platform == "darwin":
            target_dir = os.path.expanduser(
                "~/Library/Application Support/Google/Chrome/NativeMessagingHosts")
        else:
            target_dir = os.path.expanduser(
                "~/.config/google-chrome/NativeMessagingHosts")
        os.makedirs(target_dir, exist_ok=True)
        target = os.path.join(target_dir, f"{HOST_NAME}.json")
        with open(target, "w") as f:
            json.dump(json.load(open(MANIFEST_PATH)), f, indent=2)
        print(f"[OK] Registered for extension {ext_id}")
        print(f"     Manifest: {target}")
    # No restart: Chrome reads the registry value and the manifest afresh on
    # every connectNative, so the next press of the button picks this up.
    print("Done. Press the power button in the KAM TTS popup or dashboard.")
    return True


def remove(ext_id):
    """Uninstall the native-messaging host and delete the generated manifest."""
    if os.name == "nt":
        import winreg
        key_path = rf"Software\Google\Chrome\NativeMessagingHosts\{HOST_NAME}"
        try:
            winreg.DeleteKey(winreg.HKEY_CURRENT_USER, key_path)
            print("[OK] Registry key removed.")
        except FileNotFoundError:
            print("[--] No registry key found.")
    else:
        for base in ("~/Library/Application Support/Google/Chrome/NativeMessagingHosts",
                     "~/.config/google-chrome/NativeMessagingHosts"):
            p = os.path.join(os.path.expanduser(base), f"{HOST_NAME}.json")
            if os.path.exists(p):
                os.remove(p)
                print(f"[OK] Removed {p}")
    # The generated pieces go too, whichever kind of launcher was built.
    for p in (MANIFEST_PATH, LAUNCHER_EXE, LAUNCHER_SRC, LAUNCHER_BAT):
        if os.path.exists(p):
            os.remove(p)


def _parse_ext_id(raw):
    """Pull the extension id out of whatever the user pasted. Accepts the bare
    id, or the dashboard URL, since copying that out of the address bar is the
    easier thing to do. Returns None if there's no valid id in there."""
    for part in re.split(r"[/\s]+", raw.strip()):
        # Chrome displays the id in lower case, but folding it means a paste
        # from somewhere that upper-cased it still works.
        part = part.strip().lower()
        if _EXT_ID_RE.match(part):
            return part
    return None


def main():
    """CLI entry point: `register_host.py <id>` installs, `--remove` uninstalls.
    Exits non-zero on a missing or malformed id, so that setup_kam.py cannot
    carry on believing the host was registered when it wasn't."""
    args = [a for a in sys.argv[1:]]
    if args and args[0] in ("-h", "--help"):
        print(__doc__)
        return 0
    # --python takes a value, so skip that value rather than mistaking a path
    # for the extension id.
    positional, skip = [], False
    for a in args:
        if skip:
            skip = False
            continue
        if a == "--python":
            skip = True
        elif not a.startswith("-"):
            positional.append(a)
    if not positional:
        # The id is pinned by the key in manifest.json, so no argument is the
        # normal case now. Passing one is only for a build with its own key.
        ext_id = PINNED_EXTENSION_ID
        print(f"Using the pinned extension id: {ext_id}")
    else:
        ext_id = _parse_ext_id(positional[0])
        if not ext_id:
            print(f"ERROR: '{positional[0]}' is not a Chrome extension id.")
            print("Expected 32 letters in the range a-p, which you can copy")
            print("from chrome://extensions with Developer mode turned on.")
            return 2
    if "--remove" in args:
        remove(ext_id)
        return 0
    # Optional explicit Python path: --python "C:\path\to\python.exe"
    python_exe = None
    if "--python" in args:
        i = args.index("--python")
        if i + 1 < len(args):
            python_exe = args[i + 1]
    # A failed self-test is a real failure, and setup_kam.py reads this code.
    return 0 if register(ext_id, python_exe) else 3


if __name__ == "__main__":
    sys.exit(main())